from typing import Dict, List


DEFAULT_NOTICE = "联系方式、门诊时间和科室安排请以医院官网或官方公众号最新信息为准。"
UNKNOWN_EMAIL = "官网未公开"


HOSPITAL_RESOURCES: List[Dict[str, str]] = [
    {
        "region": "北京市",
        "city": "北京",
        "alias": "北京 京 北大医院 北京大学一院 北京大学第一医院",
        "hospital": "北京大学第一医院",
        "department": "精神心理科 / 心理咨询门诊",
        "phone": "010-83572211（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "北京市西城区西什库大街8号",
        "source_url": "https://www.pkufh.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "天津市",
        "city": "天津",
        "alias": "天津 津 天津医科大学总医院 天医总医院",
        "hospital": "天津医科大学总医院",
        "department": "心理门诊 / 精神心理相关门诊",
        "phone": "022-60362255（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "天津市和平区鞍山道154号",
        "source_url": "https://www.tjmugh.com.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "河北省",
        "city": "石家庄",
        "alias": "河北 冀 石家庄 河北医科大学第一医院 河北医大一院 医科大一院",
        "hospital": "河北医科大学第一医院",
        "department": "精神卫生科 / 心理咨询门诊",
        "phone": "0311-85917000（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "河北省石家庄市东岗路89号",
        "source_url": "https://www.jyyy.com.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "山西省",
        "city": "太原",
        "alias": "山西 晋 太原 山西医科大学第一医院 山医大一院 医科大一院",
        "hospital": "山西医科大学第一医院",
        "department": "精神卫生科 / 心理咨询门诊",
        "phone": "0351-4639114（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "山西省太原市迎泽区解放南路85号",
        "source_url": "https://www.sydyy.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "内蒙古自治区",
        "city": "呼和浩特",
        "alias": "内蒙古 蒙 呼和浩特 内蒙古医科大学附属医院 内医大附院 医科大附属医院",
        "hospital": "内蒙古医科大学附属医院",
        "department": "心理咨询门诊 / 精神心理相关门诊",
        "phone": "0471-3451120（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "内蒙古自治区呼和浩特市回民区通道北街1号",
        "source_url": "https://www.nmgfy.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "辽宁省",
        "city": "沈阳",
        "alias": "辽宁 辽 沈阳 中国医科大学附属第一医院 中国医大一院 医科大一院",
        "hospital": "中国医科大学附属第一医院",
        "department": "心理门诊 / 精神医学相关门诊",
        "phone": "024-961200（官方咨询，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "辽宁省沈阳市和平区南京北街155号",
        "source_url": "https://www.cmu1h.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "吉林省",
        "city": "长春",
        "alias": "吉林 吉 长春 吉林大学第一医院 吉大一院",
        "hospital": "吉林大学第一医院",
        "department": "心理卫生科 / 精神心理相关门诊",
        "phone": "0431-88782222（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "吉林省长春市新民大街1号",
        "source_url": "https://www.jdyy.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "黑龙江省",
        "city": "哈尔滨",
        "alias": "黑龙江 黑 哈尔滨 哈医大一院 哈尔滨医科大学附属第一医院",
        "hospital": "哈尔滨医科大学附属第一医院",
        "department": "精神心理科 / 心理咨询门诊",
        "phone": "0451-85556000（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "黑龙江省哈尔滨市南岗区邮政街23号",
        "source_url": "https://www.54dr.org.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "上海市",
        "city": "上海",
        "alias": "上海 沪 华山医院 复旦大学附属华山医院",
        "hospital": "复旦大学附属华山医院",
        "department": "心理医学科",
        "phone": "021-52889999（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "上海市静安区乌鲁木齐中路12号",
        "source_url": "https://www.huashan.org.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "江苏省",
        "city": "南京",
        "alias": "江苏 苏 南京 江苏省人民医院 南京医科大学第一附属医院 南医大一附院",
        "hospital": "江苏省人民医院（南京医科大学第一附属医院）",
        "department": "临床心理科 / 医学心理科",
        "phone": "025-68303126（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "江苏省南京市广州路300号",
        "source_url": "https://www.jsph.org.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "浙江省",
        "city": "杭州",
        "alias": "浙江 浙 杭州 浙江大学医学院附属第一医院 浙大一院",
        "hospital": "浙江大学医学院附属第一医院",
        "department": "精神卫生科 / 心理咨询门诊",
        "phone": "0571-87236114（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "浙江省杭州市上城区庆春路79号",
        "source_url": "https://www.zy91.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "安徽省",
        "city": "合肥",
        "alias": "安徽 皖 合肥 安徽医科大学第一附属医院 安医大一附院 医科大附属医院",
        "hospital": "安徽医科大学第一附属医院",
        "department": "精神心理科 / 心理咨询门诊",
        "phone": "0551-62922114（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "安徽省合肥市绩溪路218号",
        "source_url": "https://www.ayfy.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "福建省",
        "city": "福州",
        "alias": "福建 闽 福州 福建医科大学附属第一医院 福建医大附一 医科大附属医院",
        "hospital": "福建医科大学附属第一医院",
        "department": "心理卫生科 / 精神心理相关门诊",
        "phone": "0591-87983333（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "福建省福州市台江区茶中路20号",
        "source_url": "https://www.fyyy.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "江西省",
        "city": "南昌",
        "alias": "江西 赣 南昌 南昌大学第一附属医院 南大一附院",
        "hospital": "南昌大学第一附属医院",
        "department": "心身医学科 / 心理咨询门诊",
        "phone": "0791-88692748（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "江西省南昌市东湖区永外正街17号",
        "source_url": "https://www.cdyfy.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "山东省",
        "city": "济南",
        "alias": "山东 鲁 济南 山东大学齐鲁医院 齐鲁医院",
        "hospital": "山东大学齐鲁医院",
        "department": "心理科 / 精神心理相关门诊",
        "phone": "0531-82169114（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "山东省济南市文化西路107号",
        "source_url": "https://www.qiluhospital.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "河南省",
        "city": "郑州",
        "alias": "河南 豫 郑州 郑州大学第一附属医院 郑大一附院",
        "hospital": "郑州大学第一附属医院",
        "department": "精神医学科 / 心理咨询门诊",
        "phone": "0371-66913114（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "河南省郑州市二七区建设东路1号",
        "source_url": "https://www.zdyfy.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "湖北省",
        "city": "武汉",
        "alias": "湖北 鄂 武汉 武汉大学人民医院 湖北省人民医院",
        "hospital": "武汉大学人民医院",
        "department": "精神卫生中心 / 心理咨询门诊",
        "phone": "027-88041911（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "湖北省武汉市武昌区张之洞路99号",
        "source_url": "https://www.rmhospital.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "湖南省",
        "city": "长沙",
        "alias": "湖南 湘 长沙 中南大学湘雅医院 湘雅医院",
        "hospital": "中南大学湘雅医院",
        "department": "心理卫生中心 / 精神心理相关门诊",
        "phone": "0731-89753999（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "湖南省长沙市开福区湘雅路87号",
        "source_url": "https://www.xiangya.com.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "广东省",
        "city": "广州",
        "alias": "广东 粤 广州 中山大学附属第一医院 中山一院 中山大学一附院",
        "hospital": "中山大学附属第一医院",
        "department": "心理医学科 / 精神心理相关门诊",
        "phone": "020-28823388（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "广东省广州市越秀区中山二路58号",
        "source_url": "https://www.fahsysu.org.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "广西壮族自治区",
        "city": "南宁",
        "alias": "广西 桂 南宁 广西医科大学第一附属医院 广西医科大学一附院 医科大附属医院 医科大一附院",
        "hospital": "广西医科大学第一附属医院",
        "department": "心理卫生科 / 精神心理相关门诊",
        "phone": "0771-5356533（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "广西壮族自治区南宁市青秀区双拥路6号",
        "source_url": "https://www.gxmuyfy.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "海南省",
        "city": "海口",
        "alias": "海南 琼 海口 海南医学院第一附属医院 海医一附院 医科大附属医院",
        "hospital": "海南医学院第一附属医院",
        "department": "心理咨询门诊 / 精神心理相关门诊",
        "phone": "0898-66711900（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "海南省海口市龙华路31号",
        "source_url": "https://www.hyfyuan.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "重庆市",
        "city": "重庆",
        "alias": "重庆 渝 重庆医科大学附属第一医院 重医一院 医科大附属医院",
        "hospital": "重庆医科大学附属第一医院",
        "department": "心理卫生中心 / 精神心理相关门诊",
        "phone": "023-68811360（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "重庆市渝中区袁家岗友谊路1号",
        "source_url": "https://www.hospital-cqmu.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "四川省",
        "city": "成都",
        "alias": "四川 川 蜀 成都 四川大学华西医院 华西医院",
        "hospital": "四川大学华西医院",
        "department": "心理卫生中心 / 心理咨询门诊",
        "phone": "028-85422114（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "四川省成都市武侯区国学巷37号",
        "source_url": "https://www.wchscu.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "贵州省",
        "city": "贵阳",
        "alias": "贵州 黔 贵阳 贵州医科大学附属医院 贵医附院 医科大附属医院",
        "hospital": "贵州医科大学附属医院",
        "department": "心理科 / 精神心理相关门诊",
        "phone": "0851-86855119（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "贵州省贵阳市贵医街28号",
        "source_url": "https://www.gmcah.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "云南省",
        "city": "昆明",
        "alias": "云南 云 滇 昆明 昆明医科大学第一附属医院 云大医院 医科大附属医院",
        "hospital": "昆明医科大学第一附属医院",
        "department": "精神科 / 心理咨询门诊",
        "phone": "0871-65324888（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "云南省昆明市西昌路295号",
        "source_url": "https://www.ydyy.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "西藏自治区",
        "city": "拉萨",
        "alias": "西藏 藏 拉萨 西藏自治区人民医院",
        "hospital": "西藏自治区人民医院",
        "department": "心理咨询门诊 / 精神心理相关门诊",
        "phone": "0891-6371626（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "西藏自治区拉萨市林廓北路18号",
        "source_url": "https://www.xzrmyy.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "陕西省",
        "city": "西安",
        "alias": "陕西 陕 秦 西安 西安交通大学第一附属医院 西交大一附院",
        "hospital": "西安交通大学第一附属医院",
        "department": "精神心理卫生科 / 心理咨询门诊",
        "phone": "029-85323112（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "陕西省西安市雁塔区雁塔西路277号",
        "source_url": "https://www.dyyy.xjtu.edu.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "甘肃省",
        "city": "兰州",
        "alias": "甘肃 甘 陇 兰州 兰州大学第一医院 兰大一院",
        "hospital": "兰州大学第一医院",
        "department": "心理卫生科 / 精神心理相关门诊",
        "phone": "0931-8625200（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "甘肃省兰州市城关区东岗西路1号",
        "source_url": "https://www.lzdxdyyy.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "青海省",
        "city": "西宁",
        "alias": "青海 青 西宁 青海大学附属医院 青大附院",
        "hospital": "青海大学附属医院",
        "department": "心理咨询门诊 / 精神心理相关门诊",
        "phone": "0971-6162000（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "青海省西宁市同仁路29号",
        "source_url": "https://www.qhuah.com/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "宁夏回族自治区",
        "city": "银川",
        "alias": "宁夏 宁 银川 宁夏医科大学总医院 宁医大总院 医科大总医院",
        "hospital": "宁夏医科大学总医院",
        "department": "心理卫生中心 / 精神心理相关门诊",
        "phone": "0951-6744457（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "宁夏回族自治区银川市兴庆区胜利南街804号",
        "source_url": "https://www.nyfy.com.cn/",
        "notice": DEFAULT_NOTICE,
    },
    {
        "region": "新疆维吾尔自治区",
        "city": "乌鲁木齐",
        "alias": "新疆 新 乌鲁木齐 新疆医科大学第一附属医院 新医大一附院 医科大附属医院",
        "hospital": "新疆医科大学第一附属医院",
        "department": "心理医学中心 / 精神心理相关门诊",
        "phone": "0991-4362930（官方总机，心理咨询请转相关科室）",
        "email": UNKNOWN_EMAIL,
        "address": "新疆维吾尔自治区乌鲁木齐市新市区鲤鱼山南路137号",
        "source_url": "https://www.xydyfy.com/",
        "notice": DEFAULT_NOTICE,
    },
]


SEARCH_FIELDS = ("region", "city", "alias", "hospital", "department", "address")
DEFAULT_DISPLAY_REGIONS = ("北京市", "上海市", "广东省", "四川省", "湖北省")


def search_hospital_resources(keyword: str) -> List[Dict[str, str]]:
    keyword = str(keyword or "").strip().lower()
    if not keyword:
        return HOSPITAL_RESOURCES
    return [
        item
        for item in HOSPITAL_RESOURCES
        if keyword in " ".join(str(item.get(field, "")) for field in SEARCH_FIELDS).lower()
    ]


def default_hospital_resources(limit: int = 5) -> List[Dict[str, str]]:
    priority = [
        item
        for region in DEFAULT_DISPLAY_REGIONS
        for item in HOSPITAL_RESOURCES
        if item.get("region") == region
    ]
    if len(priority) >= limit:
        return priority[:limit]
    seen_regions = {item.get("region") for item in priority}
    rest = [item for item in HOSPITAL_RESOURCES if item.get("region") not in seen_regions]
    return (priority + rest)[:limit]
